accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import signup

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('signup/', signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

import photo

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include('accounts.urls')),

]

photo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

import photo
from photo.views import PhotoCreate, PhotoDelete, PhotoUpdate, PhotoDetail, PhotoList, PhotoLike, PhotoFavorite, \
    PhotoLikeList, PhotoFavoriteList, PhotoMyList

app_name = 'photo'

urlpatterns = [
    path('create/', PhotoCreate.as_view(), name='create'),
    path('delete/<int:pk>/', PhotoDelete.as_view(), name='delete'),
    path('update/<int:pk>/', PhotoUpdate.as_view(), name='update'),
    path('detail/<int:pk>/', PhotoDetail.as_view(), name='detail'),
    path('', PhotoList.as_view(), name='index'),
    path('like/<int:photo_id>/', PhotoLike.as_view(), name='like'),
    path('favorite/<int:photo_id>/', PhotoFavorite.as_view(), name='favorite'),
    path('like/', PhotoLikeList.as_view(), name='like_list'),
    path('favorite/', PhotoFavoriteList.as_view(), name='favorite_list'),
    path('mylist/', PhotoMyList.as_view(), name='mylist'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class SignUpForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'first_name', 'last_name', 'email']

    def clean_Repeat_password(self):
        cd = self.cleaned_data
        if cd['password'] != cd['Repeat_password']:
            raise forms.ValidationError['비밀번호가 일치하지 않습니다.']
        return cd['Repeat_password']

accounts/views.py
# from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from accounts.forms import SignUpForm


def signup(request):
    if request.method == 'POST':
        signup_form = SignUpForm(request.POST)

        if signup_form.is_valid():
            user_instance = signup_form.save(commit=False)
            user_instance.set_password(signup_form.cleaned_data['password'])
            user_instance.save()
            return redirect(request, 'accounts/signup_complete.html', {'username': user_instance.username})

        else:
            signup_form = SignUpForm()

        return render(request, 'accounts/signup.html', {'form': signup_form.as_p})


    #     username = request.POST.get('username')
    #     password = request.POST.get('password')
    #     password2 = request.POST.get('password2')
    #     print(username, password, password2)
    #
    #     # 회원 객체 생성하기
    #     user = User()
    #     user.username = username
    #     user.password = password
    #     user.set_password(password)
    #     user.save()
    #     return render(request, 'accounts/signup_complete.html')
    # else:
    #     context_values = {'form':'this is form'}
    #     return render(request, 'accounts/signup.html', context_values)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
            <div class="alert alert-primary" role="alert">
                로그인 정보를 입력해주세요. </div>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="로그인" class="float-left btn btn-outline-primary">
                <a href="{% url 'accounts:signup' %}" class="float-right btn btn-outline-primary">또는 계정 생성</a>
            </form>



    </div>
    <div class="col"></div>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
            <div class="alert alert-primary" role="alert">
                로그아웃이 잘 되었습니다. </div>
            <a href="{% url 'accounts:login' %}" class="btn btn-outline-success">로그인하기</a>
    </div>
    <div class="col"></div>

</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <form action="" method="post">
            <div class="alert alert-info">반드시 계정 정보를 기입해주세요</div>
                {% csrf_token%}
            <label>이름 : <input type="text" name="username"></label>
            <label>비밀번호 : <input type="password" name="password"></label>
            <label>비밀번호 확인 : <input type="password" name="password2"></label>
            <input type="submit" value="회원가입" class="btn btn-outline-info">
        </form>
    </div>
    <div class="col"></div>
</div>

{% endblock %}

accounts/templates/accounts/signup_complete.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col-6">

            <div class="alert alert-primary" role="alert">
                회원가입이 완료되었습니다.
            </div>
            <a href="{% url 'accounts:login' %}">로그인하기</a>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}