config/urls.py
from django.contrib import admin
from django.urls import path, include

import photo

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include('accounts.urls')),

]

photo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

import photo
from photo.views import PhotoCreate, PhotoDelete, PhotoUpdate, PhotoDetail, PhotoList, PhotoLike, PhotoFavorite, \
    PhotoLikeList, PhotoFavoriteList, PhotoMyList

app_name = 'photo'

urlpatterns = [
    path('create/', PhotoCreate.as_view(), name='create'),
    path('delete/<int:pk>/', PhotoDelete.as_view(), name='delete'),
    path('update/<int:pk>/', PhotoUpdate.as_view(), name='update'),
    path('detail/<int:pk>/', PhotoDetail.as_view(), name='detail'),
    path('', PhotoList.as_view(), name='index'),
    path('like/<int:photo_id>/', PhotoLike.as_view(), name='like'),
    path('favorite/<int:photo_id>/', PhotoFavorite.as_view(), name='favorite'),
    path('like/', PhotoLikeList.as_view(), name='like_list'),
    path('favorite/', PhotoFavoriteList.as_view(), name='favorite_list'),
    path('mylist/', PhotoMyList.as_view(), name='mylist'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='timeline_photo/%Y/%m/%d')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    like = models.ManyToManyField(User, related_name='like_post', blank=True)
    favorite = models.ManyToManyField(User, related_name='favorite_post', blank=True)

    def __str__(self):
        return "text : " + self.text

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('photo:detail', args=[self.id])

photo/views.py
from urllib.parse import urlparse

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import redirect
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from photo.models import Photo


#
class PhotoList(ListView):
    model = Photo
    template_name_suffix = '_list'


class PhotoCreate(CreateView):
    model = Photo
    fields = ['text', 'image']
    template_name_suffix = '_create'
    success_url = '/'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form': form})


class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['text', 'image']
    template_name_suffix = '_update'

    # success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '수정할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else:
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)


class PhotoDelete(DeleteView):
    model = Photo
    template_name_suffix = '_delete'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '삭제할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else:
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)


class PhotoDetail(DetailView):
    model = Photo
    template_name_suffix = '_detail'


class PhotoLike(View):
    def get(self, request, *args, **kwargs):
        # 로그인 확인
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user

                # user가 이미 좋아요 한 사람 중에 있으면 클릭했을 때 지워지도록 하고
                if user in photo.like.all():
                    photo.like.remove(user)
                # 그렇지 않으면 더하게 함.
                else:
                    photo.like.add(user)

            # referer_url을 통해서 url을 parse하여
            # 만약에 메인페이지에서 좋아요를 누르면 그 메인페이지에 있도록 하고
            # 상세페이지에서 좋아요를 누르면 그 상세페이지로 redirect하게 함.
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)


class PhotoFavorite(View):
    def get(self, request, *args, **kwargs):
        # 로그인 확인
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.favorite.all():
                    photo.favorite.remove(user)
                else:
                    photo.favorite.add(user)
            return HttpResponseRedirect('/')


class PhotoLikeList(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:  # 로그인확인
            messages.warning(request, '로그인을 먼저하세요')
            return HttpResponseRedirect('/')
        return super(PhotoLikeList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        # 내가 좋아요한 글을 보여줌
        user = self.request.user
        queryset = user.like_post.all()
        return queryset


class PhotoFavoriteList(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:  # 로그인확인
            messages.warning(request, '로그인을 먼저하세요')
            return HttpResponseRedirect('/')
        return super(PhotoFavoriteList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        # 내가 좋아요한 글을 보여줌
        user = self.request.user
        queryset = user.favorite_post.all()
        return queryset


class PhotoMyList(ListView):
    model = Photo
    template_name = 'photo/photo_mylist.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:  # 로그인확인
            messages.warning(request, '로그인을 먼저하세요')
            return HttpResponseRedirect('/')
        return super(PhotoMyList, self).dispatch(request, *args, **kwargs)

photo/templates/photo/photo_create.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <div class="alert alert-primary" role="alert">
            모든 부분을 다 채워넣어주세요!!
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token%}

            {{ form.as_p }}
            <input type="submit" value="Upload" class="btn btn-primary">
        </form>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

photo/templates/photo/photo_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="alert alert-primary" role="alert">
    진짜로 {{ object }}를 지우실 건가요?
</div>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete OK">
</form>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col-12 col-xl-4 col-md-4">
            <div class="card" style="width: 30rem;">
                <img src="{{ object.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">

                    <h5 class="card-title">{{ object.author }}</h5>
                    <p class="card-text"> {{ object.text }} </p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="{% url 'photo:like' object.id %}"
                           class="float-left btn-like {% if user in object.like.all %} active {% endif %}">좋아요!</a>
                        {% if object.like.all.count %}
                            <span class="float-left">
                        {{ object.like.all.coun }}
                    </span>
                        {% endif %}
                        <a href="{% url 'photo:favorite' object.id %}" class="float-right btn-favorite {% if user in object.favorite.all  %} active {% endif %}">저장하기!</a>
                    </li>
                    <li class="list-group-item">생성일 : {{ object.created }}</li>
                    {#                <li class="list-group-item">수정일 : {{ object.updated }}</li>#}
                    <li class="list-group-item">
                        {% load disqus_tags %}
                        <div class="card-body">
                            {% disqus_show_comments %}
                        </div>
                    </li>
                </ul>
                <div class="card-body">
                    <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                    <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

photo/templates/photo/photo_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {#            <div class="row-1"></div>#}
            <div class="col"></div>
            <div class="col-5">
                {% for object in object_list %}
                    <div class="card-header">
                        {{ object.author }}
                    </div>
                    {#                    <img src=" {{ object.image.url }} " class="card-img-top" style="height: auto; width: 100%; border:1px solid black;" alt="...">#}
                    <img src=" {{ object.image.url }} " class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text">{{ object.text }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            {% if user.is_authenticated %}
                                <a href="{% url 'photo:like' object.id %}"
                                   class="float-left btn-like {% if user in object.like.all %} active {% endif %}">좋아요!</a>
                            {% endif %}
                            {% if object.like.all.count %}
                                <span class="float-left">
                                    {{ object.like.all.count }}
                                </span>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <a href="{% url 'photo:favorite' object.id %}"
                                   class="float-right btn-favorite {% if user in object.favorite.all %} active {% endif %}">저장하기!</a>
                                </li>
                            {% endif %}
                        <li class="list-group-item">생성일 : {{ object.created }}</li>
{#                        <li class="list-group-item">수정일 : {{ object.updated }}</li>#}
                    </ul>
                    {% if user.is_authenticated %}
                        <div class="card-body">
                            <a href="{% url 'photo:detail' object.id %}" class="card-link">댓글달기</a>
                            {% if user == object.author %}
                                <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                                <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

            <div class="col">
            {% if user.is_authenticated %}
                {% load static %}
                <div class="card" style="">
{#                TODO 프로필을 만들어야 사진이 바뀔듯.. #}
                    <img src="{% static 'images/awos.JPG' %}" class="card-img-top">
                    <div class="card-body">
{#                        {% for object in object_list %}#}
{#                            {% if forloop.first %}#}
{#                                {% if object.author == request.user %}#}
{#                                    <h5 class="card-title">{{ object.author }}</h5>#}
{#                        TODO 글없을 때에도 username이 나오도록 하기 #}
                                    <h5 class="card-title">{{ request.user }}</h5>
{#                                {% endif %}#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
                        <p class="card-text">회원님의 스토리를 확인해보세요!</p>
                        <a href="{% url 'photo:mylist' %}" class="btn btn-primary">회원님의 스토리 이동</a>
                    </div>
                </div>
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

photo/templates/photo/photo_mylist.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
    <style>

    </style>

    <div class="container">
        <div class="row mx-auto">
            {% if object_list %}
                {% for object in object_list %}
                    {% if object.author == request.user %}
                        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                        <div class="card text-center" style="min-width: 18rem;">
{#                        <a href="{{ object.id }}"><p class="card-img-top my_image">{{ object.image|safe }}</p></a>#}
                            <a href="{% url 'photo:detail' object.id %}"><img src="{{ object.image.url }}"
                                                                              class="card-img-top my_image"
                                                                              alt="..."></a>
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="row mx-auto">
                    <p>올린 글이 없습니다.</p>
                </div>
            {% endif %}
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post">
            {% csrf_token%}
            {{ form.as_p }}
            <input type="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}